### ISSUE TITLE
psr/container v2?

### ISSUE THREAD

**Issue by route33** [woohoolabs/zen#14]
Do you plan to support psr/container v2 any time soon?

**Comment by kocsismate** [comment]
Yes, I'd like to add support for v2, however the problem is that I am critically short of time these days. If you are willing to provide a PR, then I may be able to review it and release a new version sometime soon. Otherwise, I'll try it in January

**Comment by route33** [comment]
@kocsismate https://github.com/woohoolabs/zen/pull/15

**Comment by kocsismate** [comment]
Fixed :)
