### ISSUE TITLE
Add scalar constructor parameters

### ISSUE THREAD

**Issue by adriansuter** [woohoolabs/zen#4]
Hi @kocsismate 

Wouldn't it be nice to be able to define at least scalar parameters to constructors?

Let's assume to have a class `Foo` which needs a string (scalar type) as first parameter called `$bar`.
```php
/**
 * Class Foo.
 *
 * @package App
 */
class Foo
{
    
    /**
     * @var string
     */
    private $bar;

    /**
     * Foo constructor.
     *
     * @param string $bar
     */
    public function __construct(string $bar)
    {
        $this->bar = $bar;
    }

}
```

Unfortunately this can not be compiled with zen (other than defining a super class with no params which then calls the constructor of its parent).

So I thought it would be nice to be able to define in the `getEntryPoints()` method of the `ContainerConfig` class the constructor values that should be compiled into.

```php
class ContainerConfig extends AbstractContainerConfig
{

    /**
     * @return EntryPointInterface[]
     */
    protected function getEntryPoints(): array
    {
        return [
            new WildcardEntryPoint(__DIR__ . '/../Controllers'),
            new ClassEntryPoint(Foo::class, ['bar' => 'Hello World']), // <- Second param takes the values as array we would like our compiler to set as default constructor values.
        ];
    }

   [...]

}
```

So the compiler would generate the following method in the container (`Foo` lives in the `App` namespace):

```php
    public function App__Foo()
    {
        return $this->singletonEntries['App\Foo'] = new \App\Foo(
            "Hello World"
        );
    }
```

What do you think?

Best regards
@adriansuter

**Comment by kocsismate** [comment]
Hi @adriansuter,

I like your idea, and it doesn't seem difficult a task to do. However, I am a little bit busy these days with other OS projects of mine, so I can only implement this feature in the near future.

But if you have the time and energy to work on it, I am happy to accept a PR. :)

**Comment by adriansuter** [comment]
See #5

**Comment by kocsismate** [comment]
I am closing this issue as I've just added support for the feature :) It will take place in v2.5, which is to be released soon!

**Comment by adriansuter** [comment]
Wonderful.
